name: go_router
description: A declarative router for Flutter based on Navigation 2 supporting
  deep linking, data-driven routes and more
version: 2.2.9
repository: https://github.com/csells/go_router

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.7.0
  path_to_regexp: ^0.4.0

dev_dependencies:
  all_lint_rules_community: ^0.0.4
  flutter_test:
    sdk: flutter
