# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options
include: package:lints/recommended.yaml

linter:
  rules:
    - avoid_redundant_argument_values
    - prefer_expression_function_bodies
    - prefer_relative_imports
    - require_trailing_commas
