name: go_router_builder
description: >-
  A builder that supports generated strongly-typed route information for
  package:go_router
version: 1.0.0-dev
repository: https://github.com/csells/go_router

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  analyzer: '>=2.7.0 <4.0.0'
  async: ^2.8.0
  build: ^2.0.0
  build_config: ^1.0.0
  collection: ^1.14.0
  meta: ^1.7.0
  path: ^1.8.0
  path_to_regexp: ^0.4.0
  source_gen: ^1.0.0
  source_helper: ^1.3.0

dev_dependencies:
  all_lint_rules_community: ^0.0.4
  build_runner: ^2.0.0
  # This is a "fake" package to enable testing
  go_router: any
  source_gen_test: ^1.0.0

dependency_overrides:
  go_router:
    path: _go_router_fake
