name: validate

on:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"

defaults:
  run:
    working-directory: go_router

jobs:
  style:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: "Install Flutter"
        run: ../.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ../.github/workflows/scripts/install-tools.sh
      - name: "Dart Analyzer"
        run: dart analyze . --fatal-infos
      - name: "Formatting Check"
        run: |
          flutter format .
          ../.github/workflows/scripts/validate-formatting.sh

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: "Install Flutter"
        run: ../.github/workflows/scripts/install-flutter.sh stable
      - name: "Install Tools"
        run: ../.github/workflows/scripts/install-tools.sh
      - name: "Flutter Test"
        run: flutter test --reporter expanded --coverage
      - name: "Upload test coverage to Codecov"
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info

  test_builder:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        sdk: [2.14.0, dev]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: ${{ matrix.sdk }}
      - id: install
        run: dart pub get
        working-directory: go_router_builder
      - run: dart test
        working-directory: go_router_builder

  test_builder_example:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - name: "Install Flutter"
      run: ../.github/workflows/scripts/install-flutter.sh stable
    - name: "Install Tools"
      run: ../.github/workflows/scripts/install-tools.sh
    - run: flutter test -x presubmit-only
      working-directory: go_router_builder/example
    - run: flutter test --run-skipped -t presubmit-only
      working-directory: go_router_builder/example
